### ISSUE TITLE
Notebooks for the live the demonstration

### ISSUE THREAD

**Issue by oloapinivad** [DestinE-Climate-DT/AQUA#1091]
### Discussion

As discussed as the today AQUA meeting, the ECMWF requires a 1-hour live demonstration (further details will come soon) where we need to showcase the AQUA diagnostics.

It has been agreed to have a main notebook using hyperlinks to diagnostic-specific notebook. Each of this notebook should include the main capabilities of the diagnostic, based more or less on what is already currently available. Since we have to show 12 diagnostics, we should consider to have approx 5-minute for each notebook, so it would be great if each diagnosti. developer can double check that everything is working as expected in a reasonable amount of time. For example, if your analysis require a lot of data processing, it will be nice if results can be cached (this can be done by using NetCDF intermediate files, or pickle, or any other option you believe it is useful)
Please also leave some clear instruction how to run or if some option can be modified live, since it will likely be only @ghosh97 @portegam and me present on the day of the demonstration. 

Please notice that there is no need to create a new notebook, rather to polish/refine the notebook that we already have at disposal. 

### Open issues

- [ ] We might want to add as introduction a notebook showing the basic AQUA functionalities since we have some of the available and could help the presentation (@silviacaprioli, could check if some of the old notebook can be used?)
- [ ] We need to explore if it is possible to use the aqua slurm functionality (@NataNazar please let me know if you think is doable)

All the notebook should be ready by the end of this week (Sunday 28th April). Please mark here below once you have prepared the notebook!

### Frontier

- [x] SSH @Jaleena 
- [x] Tropical rainfall @NataNazar #1112, `for_live_demonstration.ipynb` 2 minutes  in a login node
- [ ] Tropical cyclones @paologhinassi 

### State-of-the-art

- [x] Mean bias @ssayedwd use #1095 `Demonstrator_D340_714.ipynb` takes 3 min with plev (last cell), 1 without
- [x] Radiation budget @ssayedwd  #1095 use `IFS_NEMO_and_ICON.ipynb`, 2.50 min 
- [x] Timeseries @mnurisso #1093 use `global_time_series.ipynb` 3.10 minutes in a login node
- [x] Sea ice @fmassonn 
- [x] Performance indices @oloapinivad #1139 
- [x] Ocean @ghosh97 https://github.com/DestinE-Climate-DT/AQUA/pull/1103
    |         | ocean drift | ocean circulation |
    |---------|-------------|-------------------|
    | levante     | 5 min       | 1.2 min           |
    | lumi    | 3.8 min     | 5 min             |

- [x] Teleconnection @mnurisso #1093 use `demonstration.ipynb` 1 minute in a login node

If there are other ideas or suggestions, please use this thread to discuss them!
