### ISSUE TITLE
Roadmap to AQUA Open Source

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#1118]
### Discussion

We had an offline discussion with the AQUA core team in order to understand which may be the steps needed to make AQUA open source and as much flexible and easy to use as possible for new users also trough conda and pypi.
Here a summary of the discussion and needed steps, splitted in task so that new issues can be created when dealing with the different aspects.

## To do list

Here a to do list to split in issues. The order is approximately the order of development.

- [x] `$AQUA_CONFIG` as first one, then`$HOME/.aqua` as second place where to look for configuration and catalogue files. This is needed since conda and pip installations will not deploy the source code where the user can easily find it so we want to gradually switch our current strategy to a machine generic approach. @mnurisso #1131 
- [x] #1123 @oloapinivad #1134
- [x] remove any machine name depencency, relative paths are specified while doing `aqua-init` or with config file modification #1125 @NataNazar -> to rethink. We keep machine and catalogs as suggested in #1186 
- [x] #1124
- [x] extract the catalogue as a new repository. This will allow to download only the models/exp/sources that the user want, with some tools specifically developed available #451 [Here new repo](https://github.com/DestinE-Climate-DT/Climate-DT-catalog)
- [x] Tool to download and add catalogue from the external repo #1182 
- [x] Develop a **catalogue merger**: this tool will allow us to go further the machine catalogue structure we have now and merge the catalogues the user wants to deploy in the machine in a single one, checking if duplicate sources are found. #1186 seems to be enough and we can avoid the development of a catalog merger.
- [x] #1239 discussion expanded there
- [x] the `aqua-config.yaml` file should become a template file #1203 
- [x] Documentation on `readthedocs` #1699 
- [x] Multiple catalog handling by `Configurer()` class #1205 

### Catalogue refactory

Single repository, where in the main you have all the structure you have in our actual catalogue and an action that for a merge checks that the catalogue merger does not encounter any issue (model, exp, source triplets not duplicated). The merger has to actually update/create a common catalog.yaml file with updated sources.

### `aqua-init` and entry points

Installing will first ask the user for a GRIDS_PATH with suggestions about considering a big amount of data and checking with a group for a common folder. If a new catalogue is added, it asks for replacement of the GRIDS_PATH already available.
 If `.aqua` is not chosen by the user as a target folder when using `aqua-init`, do a soft-link and create `.aqua`.
Can make sense as unique entry point aqua-catalogue or something similar with options add, update and remove

- [x] If a custom path instead of `.aqua/` is requested while doing `aqua-init` a link to this new path is added in a created .aqua/ folder.
- [x] `aqua-add {CATALOG}` can take care of downloading the right available online catalogue or from a path provided
- [x] `aqua-update {CATALOG}` that checks if new grids and catalogue files are available.
- [x] `aqua-remove  {CATALOG}` can do a cleanup of a dismissed catalogue.
- [x] The entry points will have a `-d` or `-i` flag for developers, so that it's possible to link locally available catalogues on local folders for development reasons.

### New .aqua content

Schema of the expected .aqua folder content after refactory:

- `config-aqua.yaml` -> installed with the `aqua-init` entry point
- `fixes` files (deployed accordingly to the installed catalogues or in first instance simply downloaded totally)
- `data_models` (same as fixes files)
- `aqua-grids.yaml` -> now the `grids` folder 
- `catalogue` -> only selected folders.

## Secondary goals

- [ ] check if the intake catalogue can be eventually read online without need to deploy it on the machine where AQUA is installed
- [ ] loglevel standard level defined at the config file level for better development functionalities
- [x] decide if *catalog* or *catalogue* is the keyword we use in AQUA and update the code and documentation accordingly
- [x] #1240
- [x] ~~CI catalogue is shipped in AQUA and available with `aqua-init -d`~~
- [x] new catalogue added can add a new folder for GRIDS_PATH. Similar result is obtained in #1186

**Comment by mnurisso** [comment]
Everything planned has been done, we're open, closing this issue!
