### ISSUE TITLE
Further improvements associated with AQUA CLI

### ISSUE THREAD

**Issue by oloapinivad** [DestinE-Climate-DT/AQUA#1167]
### Feature request

Some open points:

- [x]  revisit the config-aqua.yaml #1186 
- [x]  make use of the grids in the config-aqua.yaml (deprecated idea)
- [x] split the `add` catalog into two different cases for editable and not
- [x] Check `_file_add` safety check on file at L284 why is not used
- [x] `aqua update` could be added so that if editable a warning is raised, if copied a new copy is done
- [x] aqua add should list the available catalogues if an invalid one is provided
- [x] update the docs accordingly to #1134 
- [x] `aqua fixes-remove` and `aqua grids-remove` to clean existing grids
- [x] `aqua list grids` and `aqua list fixes` to know what is installed (modify to aqua list catalog or something like that)
- [x] Retrieving catalogs from Github remote #1182
