### ISSUE TITLE
Roadmap for open source: diagnostics, scripts and other details

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#1242]
# Discussion

Following the offline discussion had a few point to solve for the development of AQUA and refactory of the diagnostics after the core has been adapted.

Important: here with diagnostics we describe only the state-of-the-art diagnostics, that have a potential similar structure and the possibility to have a standardize approach on cli 

## To do: phase1

note: a point is closed if a proper issue is created or it has been solved.

- [x] #1239 
- [x] `catalog` keyword introduced for all the diagnostics cli
- [x] #1283
- [x] investigate if the actual aqua console parser and subparser structure can accomodate the idea of not used command line arguments given to the subcommand, so that` aqua lra --model=IFS-NEMO` will give the `--model` arg to the cli_lra.py seamless. #1294
- [x] Follow up of #1199, now that config files are exposed, we need to be sure these are the ones automatically used by the diagostics
- [x] template and config folder in the aqua repo, where template is for files that demand a modification of the original provided file, while config files is made of default files that can be used out of the box and eventually customized. The files have to be copied while the console is installing aqua #1294 has an initial sketch of this change

## To do: phase2

- [x] move notebooks out of the diagnostics core folders
- [x] single pyproject file for all the diagnostics
- [x] cli all together in the same diagnostics/cli folder, so that a single console is possible
- [ ] aqua-diagnostics console that can call as entry points the individual CLIs

## To do: phase3

- [x] complete refactor of `aqua-analysis.sh` based on the aqua-diagnostics console that we'll introduce in phase2. The goal is to get rid of any bash script in fundamental parts of the code. To be understood how it can work the actual parallelization structure with such a solution

## To remember when making open source

- [x] invalidate all access tokens

## Secondary goals

- [x] While refining diagnostics, go towards the direction introduced in #1243, class for the analysis, but consider reader and preprocess (regrid or similar) to be done in the corresponding cli, with the possibility of very standardize cli structure
