### ISSUE TITLE
Release v0.11

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#1291]
### Discussion

We're aiming at releasing a v0.11

## To do:

- [x] Preparation PR #1292 
- [x] Solve #1286 with #1287 
- [x] Solve #1285 with #1288 
- [x] Revert eccodes due to #1282, a more long term solution will be found after vacation
- [ ] #1281 to be checked
- [x] New catalog generator as requested in #1265
