### ISSUE TITLE
Changes to aqua-web and AQUA to prepare for dashboard

### ISSUE THREAD

**Issue by jhardenberg** [DestinE-Climate-DT/AQUA#1401]
### Discussion

As discussed today, there is few changes which I would like to make to aqua-web code and functionality so that we separate more and more concerns (we minimize needed changes) between the two and in preparation to shifting everything to the dashboard.
I list some here, we can discuss below and complete the list if needed. These should then trigger PRs (also separate ones). I will post below a more detailed description of each issue.

Why are we doing this? Because this will help us to identify what is info which AQUA should provide (or which should be in the catalogues) and which info should be in aqua-web (or the dashboard)

List of issues:

- [x] move make_contents.py to AQUA/cli/aqua-web/push_analysis.sh or aqua-analysis.sh(or py). #1470 
- [x] remove experiment-specific info from config.yaml in aqua-web. #1633
- [x] add experiment title and description to existing catalogue entries. #1633 https://github.com/DestinE-Climate-DT/Climate-DT-catalog/pull/115
- [x] let the automatic catalogue generator add also metadata to the catalog entry #1637 
- [x] write function to provide description and title from catalogue. #1633
- [x] modify make_content.py to include description and title. #1573 
- [x] Push figures to LUMI-O #1582 #1607  https://github.com/DestinE-Climate-DT/aqua-web/pull/78

Later step:

- [ ] The content.yaml file could be created directly by aqua-analysis.sh/py
