### ISSUE TITLE
Dummy diagnostic improvements

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#292]
### Discussion

- [x] `README` updated with these modifications see #300 
- [x] `README` file motivation section. Describe scientifically main output of the diagnostic. see #300 
- [x] `README` section with notebook description. 2-3 sentences for each notebooks. see #300 
- [x] how to install more general (levante, lumi), also in the `README` see #300 
- [x] data requirement section (regrid, time aggregation used as a standard) see #300 
- [x] few lines in the env file about how to create see #294 
- [x] ~~`pip install` of aqua so that requirements are aligned~~ (already present)
- [x] ~~clear explanation on how to work on lumi with different environments~~ I'd address it in #299 
- [x] clear docstring example and info on `README` file see #300 
- [x] class example using external functions on another `file.py` see #294 
- [x] command line interface using the class see #307 
- [x] notebooks updated to the class structure see #302 
- [x] hyperlinks and structure of the notebook at the beginning of the file see #302 
- [x] documentation working according to #288 see #297 

@NataNazar will take care of the `README_template`.
@mnurisso will take care of lumi environments
@oloapinivad will take care of command line interface
@mnurisso  will take care of the class example
@NataNazar will take care of notebook example refactor
@paologhinassi will take care of documentation update 

Each feature improvement will be a PR to the main.
