### ISSUE TITLE
AQUA release v0.4

### ISSUE THREAD

**Issue by oloapinivad** [DestinE-Climate-DT/AQUA#481]
### Discussion

This is to document the progress toward the new release.
things to be completed are listed here. 

- [ ] Merge all target PR
- [x] Update the changelog #564 
- [x] #565 done in #564 
- [x] Update the container name #564 
- [x] Update dropdown menu of bug report #564
- [x] Check all the Reader notebooks #564
