### ISSUE TITLE
Radiation diagnostic technical and scientific improvements

### ISSUE THREAD

**Issue by oloapinivad** [DestinE-Climate-DT/AQUA#550]
### Feature request

There are a few improvements that might be useful for the `radiation` diagnostic code, both from the technical and from the scientific side. Indeed, while developing the CLI with @NataNazar we found some issues in the way functions are implemented that might be worth to improve.

To give some suggestion/guidance in how to do this, we created in the `cli/radiation-more` branch a new file named `radiation_function.py` where a few functions  (namely  `new_process_ceres_data()`, `new_process_model_data()` and `new_barplot_model_data()`) has been introduced to be used in the `barplot` notebook. We hope that this approach will help to develop functions more integrated in the AQUA framework and with simpler usage and code. Overall, what has been done for the `atm_global_mean` diagnostic is much more aligned, but please have a look also at other diagnostics.

I will keep this issue open also to keep track of the things that might be useful to improve, from both the technical and scientic point of view

## Technical

- [x] For plotting purposes, please exploit packages like https://seaborn.pydata.org/ which provide very nice plotting routines based on pandas. 
- [ ] There's a performance warning while executing the CLI (but since it's very fast I don't think it's particularly problematic)

## Scientific and graphical
- Barplots: 
    - [x] They should be grouped by variables so that you can have an easier comparison (see[ this example](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.statology.org%2Fseaborn-grouped-bar-plot%2F&psig=AOvVaw2vlzYr0r97g5434heTuGOD&ust=1696697055363000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCIiDgJzv4YEDFQAAAAAdAAAAABAE))
    - [x] It would be great to use box plots instead of bars so that we can estimate the interannual variability (see [this example](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.geeksforgeeks.org%2Fhow-to-manually-order-boxplot-in-seaborn%2F&psig=AOvVaw3RWm38J06CCIAjhi5JlVyI&ust=1696696984658000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCNjMqfru4YEDFQAAAAAdAAAAABAI))
    - [x] #964
    - [x] The histogram plot is very useful, but it will be great if this can transformed into a box plot so that we have a measure of uncertainity
- [x]  Add the possibile of doing season-average for mean bias plots
- [x] Add a measure of uncertainity as a statistical plot

<details>
<summary><b>Completed</b></summary>

Technical

- [x] Exploit all the features provided by the Reader and general AQUA features such as the ones available in `aqua.util` in your internal functions (e.g those in `radiation-functions.py`). For example in  terms of fixing capabilities and regridding from  AQUA. If a fixing does not exist for some dataset (as CERES), this can be implemented, please just request it, no need to do so 'locally'. To regrid, use the reader capabilities and do not call external tools like cdo. #566 #537 
- [x] Please use as much as possible the GRIB convention from the LRA (variable names, units), so that you do not have to rename variables. This will simplify the pipeline and make the output cleaner. #537 
- [x] Functions should be as much flexible and general as possible, so for example names of models should not be hard-coded inside  the functions and dates or years should not be hardcoded but should rather be passed as keywords/parameters. Ideally, it should be possible to use the same functions also for future experiments or with other observational datasets, without modifications. #537
- [x] Always set default values for the keys in the functions if they can be optional (as `function(data, test=key)`, that is use key arguments instead of positional arguments as much as possible (where it makes sense) #537 
- [x] Avoid if possible multiple returns with different variables, but rather exploit dictionaries or lists. #537 
- [x] ICON and another model comparisons are hardcoded. Models to be analyzed should be userdefined #537 

Scientific

</details>
