### ISSUE TITLE
Ocean3d diagnostic technical and scientific improvements

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#553]
### Feature request

The CLI provided in #530 is going to be merged soon.  While testing it we found a couple of improvements that we'd like to implement in the ocean3d code.

## Tier1

- [x] Multilevel trend and zonal mean trend do not respect the same name structure as the other images, you can homogenize them to the other names or viceversa
- [x] In the multilevel trend cbar are set around zero, but 0 is not assigned to the white color, but it's the distinction between first shade or red and first of blue. Can you add one level and make zero the center of the white shade.
- [x] Hovmoller plot: not all the symmetric colorbar are set around zero, plus the same problem as the multilevel trend
- [x] #965
- [x] Zonal trend: same cbar problem as multilevel trend

### Technical

- [ ] Define a common range for potential temperature or salinity anomalies for colorbars (it will be great if this can be set up from the configuration file)
- [ ] Join into a single plot all the different months stratifications (and perhaps provide only one for FMA by default)

### Scientific
- [ ]  For the 2D plot there is no control of the colorbar limits while doing comparison between multiple levels or multiple experiments (I mean linear trends of T,S, each level has the colorbar independent, difficult to compare)
- [ ] Rationalize number of plots (before some function was unused, now multiple very similar plots are produced
- [ ] Is the actual setup of chosen regions scientifically the most relevant or it was for testing purposes?
- [ ] Perhaps use log-y axis to highlight surface changes (we will have short runs and deep ocean changes will be small)
- [x] Reduce the number of default plots for Hovmoller (perhaps keep only anomaly and std. anomaly from initial time) and allow use to configure for more plots. So far too many plots are produced.

I'm opening this issue to not forget about them and to fix them when @ghosh97 will be back from vacation.
In the meanwhile thanks for the CLI and it will be soon in the AQUA code!

<details>
<summary><b>Completed</b></summary>

Technical

- [x] The naming of figures, handled by `dir_creation` utility function, does not follow the scheme of #364 or #351, in particular info of the model-exp analyzed is missing. The function should be modified accordingly
- [x] The `loglevel` is hardcoded as `'INFO'`, so if we want to set a higher or lower level while running the CLI this is not possible
- [x] `__init__` file is importing everything from every file, you should select which functions you want to make visible from outside the package and import only them in this file
- [x] There's the option `warnings.filterwarnings("ignore")` at the top of your library files. Which warning where you getting? There may be something worth to solve
- [x] Add region selection from configuration file, now this is hardcoded #578 
- [x]  Some of the functions are not used (zonal ones), while the CLI is perfectly working, we'd like to expand the plots it can produce, exploiting all the functionalities that have been introduced #578 
- [x] #774 

Scientific

- [x] Plots are being weird on the time-axis. There is a bit of problems with many years of observations, ticks of the axis are a bit problematic to read. Example of the output problem can be seen here: `/scratch/b/b382289/cli_test` on levante #578 
- [x] Labels for the colorbars in the Hovmoller plots are missing #578 
- [x] Provide more significant regions as default (e.g. Labrador Sea)

</details>
