### ISSUE TITLE
SeaIce diagnostic technical and scientific improvements

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#555]
### Feature request

The CLI of #549 is almost ready to be merged but it would require some refinements. Here we provide a couple of improvements that we'd like implement in the Sea Ice diagnostic.

## Scientific
(some of them might be obsolete following new updates)

- [x] It would be nice to have 2D polar plot showing the sea ice concentration and sea ice thickness #932 
- [x] timespan for custom years selection is in the configuration file but not active when defined
- [x] Probably there is no need to plot the entire time series of the observational data especially, if the two times are not overlapping

<details>
<summary><b>Completed</b></summary>

Technical

- [x] Give the possibility while executing the CLI to choose which region should be evaluated, but by default the CLI should analyze all of them #549 
- [x] The output directory is not fully user-defined. While executing the CLI at the moment the output directory is used to save the netcdf files but images are stored in the folder in which the CLI is being executed. #549
- [x] Plot labels are not referred to the dataset requested by the CLI arguments. In my tests I used: `model='FESOM', exp='tco2559-ng5-cycle3', source='lra-monthly-r100'` and the labels on the plot refers to the standard source described in the config files. So I'm not 100% sure if only the labels are wrong or wrong data are accessed (from a quick look it should be the first case) #549
- [x] Error handling: check other diagnostics, your CLI should not fail if data are missing, are not enough (since your plotting timeseries this probably means at least two months of data I guess) and if observations to compare with are missing.
- [x] Comparison with observations: from my tests with `model='FESOM', exp='tco2559-ng5-cycle3', source='lra-monthly-r100'` I didn't see any comparison with observations. This should always happen or eventually raise a warning message if the comparison is not possible. #549
- [x] OSI-SAF siconc conversion to ci should be handled by AQUA fixer and not inside the code

Scientific

- [x] The plots are lacking a comparison with observation #549 

Tecnical

- [x] #596
- [x] An estimate of the uncertainity - perhaps deduced from observation dataset, a sort of 5-95 confidence level could be implemented. 
    - [x] Use OSI-SAF to provide a ribbon of plausible values which can be used as uncertainity
    - [x] Or use a second observational dataset in figures
    - [x] Provide seasonal cycles of sea ice extent, not raw time series
- [x] #597

</details>
