### ISSUE TITLE
Timeseries technical and scientific improvements

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#562]
### Feature request

The CLI introduced in PR #534 is in the main. We have some improvements that we list here in order to take care of them.

## Technical

- [ ] Add information in the caption that the shading is +/- 2 sigma
- [ ] Save 1990-2020 precomputer values for ERA5 and CERES Gregory plot bands to save time in the wrapper.
- [x] Expose the region field in config e CLI #1564 
- [x] better handling of model reference description, there are still hardcoded names
- [x] catalog is not correctly used by the aqua-analysis while calling the timeseries cli

## Scientific

- [ ] sos variable need a dataset different from ERA5 if we want to compare it with observations (#1090 added ESA-CCI, the default yaml file for data comparison should be updated and tested)

<details>
<summary><b>Completed</b></summary>

## Technical 

- [x] Default comparison is done with the ERA5 data. While this will still be the standard case, it may be useful to generalize the dataset to compare with
- [x] Add time-value grids to plot to simplifiy readability #637
- [x] Confusion between `extend` and `expand` in arguments in the class #1299 
- [x] Produce also timeseries for latitudinal bands, e.g. NH (30N-90N) and SH (90S-30S) hemisphere #1299 

## Scientific

- [x] A measure of uncertainty is lacking. A ribbon showing the variance (something as 5%-95% confidence of observational variance over a certain standard period) will be very useful (this can be also precomputed and stored in the yaml file) #637
- [x] Timeseries can be plot only for individual variables. It would be cool to be able to plot timeseries for derived quantity, such as sums or subtractions of two variables. #637 introduced the feature, but since it's not done for ERA5 as well plots are failing
