### ISSUE TITLE
Teleconnection technical and scientific improvements

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#575]
### Feature request

As for the other diagnostics, we create a specific issue to detail suggested improvements

## Technical

- [x] Keep attributes, update new attribute and general refinement of netcdf store system. There seems in particular to be an issue when saving the statistical maps that doesn't preserve the variable name in the stored netCDF
- [ ] save_png and save_pdf flags should save the image when True and not in the CLI

## Scientific

- [ ] Power spetra from index

## Low Tier

- [ ] `regional_anomalies_cdo` test function to complete
- [x] MJO new teleconnection analysis #247
- [ ] does it make sense to have the possibility to detrend avg_tos for ENSO in scenario run?
- [ ] Automatic creation of concordance map when running the bootstrap CLI
- [ ] MJO CLI

<details>
<summary><b>Completed</b></summary>
Technical

- [x] cbar for regression and ylim set as default in the config file #1018 
- [x] Compact CLI #574 
- [x] Multiple exps comparison #574
- [x] Performance increase #571 (see issue #569 and #547)
- [x] Rationalize logger hierarchy #574 
- [x] Add tests with season selection #581 
- [x] reg/cor for ENSO swapped #592
- [x] #775
- [x] Save NAO plot with hPa and not Pa (and introduce automatic units check) #924 
- [x] bootstrap test 

Scientific
- [x] Confidence between ERA5 and models in regression and correlation maps #1026 
- [x] `DJF` selection for regression and correlation (and expansion to generic month triplet). #581 
- [x] Define a common colourbar range for all the plots with the paerson coefficient between -1 and 1 to simplify plots comparison #592 
</details>

**Comment by oloapinivad** [comment]
This is pretty old can be closed. Further updates are planned only for power spectra.
