### ISSUE TITLE
Wrapper updates from workflow feedback

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#697]
### machine

Lumi

### version

main

### What happened?

We have from feedback on what to improve of fix in the wrapper:

- [x] logger files are always opened appending new run logs, but this makes very difficult to read new results, we suggest to switch to overwrite #698 
- [x] some diagnostics seem to suffer from renaming or moving that was done in #684 we need to check they work correctly. From the workflow it seems a couple of them need changes.
- [x] Add a logfile for dummy diagnostic as well #698 
- [x] Teleconnections runs both on oceanic and atmospheric data so that log files are still written together, same for time series, @NataNazar will try to give a look to it.

### Are you interested in making a pull request?

Yes
