### ISSUE TITLE
Update v0.5.2 of AQUA: roadmap

### ISSUE THREAD

**Issue by mnurisso** [DestinE-Climate-DT/AQUA#732]
- [x] target PR are merged #713 
- [x] necessary issues are solved #735
- [x] update changelog
- [x] update container name
- [x] update bug report menu
- [x] update version number on `__init__` AQUA file
- [x] gsv to pin at 0.11.1
- [x] Fix tests accordingly to the gsv pin
- [x] remove issue about version update, not working
- [x] typo in changelog description of issue #703
- [x] #747
